name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - name: Xcodebuild Debug
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: GenI2C.xcodeproj
          # scheme: # optional
          # destination: # optional
          configuration: Debug
          build-settings: -target BuildAll
          action: build
      - name: Xcodebuild Release
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: GenI2C.xcodeproj
        # destination: # optional
          configuration: Release
          build-settings: -target BuildAll
          action: build
      - name: Upload to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/*/*.zip
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*/*.zip
          tag: ${{ github.ref }}
          file_glob: true     
